### ISSUE TITLE
Migration fails second inspection pass of LUKS partition after initial success

### ISSUE THREAD

**Issue by stefanSpectro** [kubev2v/forklift#3033]
We are trying to migrate a VM which contains many LUKS partitions.  Initial inspection pass/unlocking of LUKS partitions succeeds fine with the temporary keys created

```
commandrvf: cryptsetup luksUUID /dev/vg_arch/lv_arch
libguestfs: trace: v2v: luks_uuid = "67240fbd-c216-47a1-8fb3-bea96884b0fa"
libguestfs: trace: v2v: cryptsetup_open "/dev/vg_arch/lv_arch" "***" "luks-67240fbd-c216-47a1-8fb3-bea96884b0fa"
guestfsd: => luks_uuid (0x1fb) took 0.02 secs
guestfsd: <= cryptsetup_open (0x1fc) request length 160 bytes
commandrvf: stdout=n stderr=y flags=0x0
commandrvf: udevadm --debug settle -E /dev/vg_arch/lv_arch
SELinux enabled state cached to: disabled
No filesystem is currently mounted on /sys/fs/cgroup.
Failed to determine unit we run in, ignoring: No data available
command: blkid '-c' '/dev/null' '-o' 'value' '-s' 'TYPE' '/dev/vg_arch/lv_arch'
command: blkid returned 0
command: blkid: stdout:
crypto_LUKS
command: cryptsetup '-d' '/tmp/cryptabdb83.key' 'open' '/dev/vg_arch/lv_arch' 'luks-67240fbd-c216-47a1-8fb3-bea96884b0fa' '--type' 'luks'
commandrvf: stdout=n stderr=y flags=0x0
commandrvf: udevadm --debug settle
SELinux enabled state cached to: disabled
No filesystem is currently mounted on /sys/fs/cgroup.
Failed to determine unit we run in, ignoring: No data available
guestfsd: => cryptsetup_open (0x1fc) took 0.15 secs
libguestfs: trace: v2v: cryptsetup_open = 0
```

However further along in the process it seems that access to this key is lost when attempting to process the same volume.  virt-v2v attempts to prompt for passphrase in a non-interactive environment and fails.

```
commandrvf: cryptsetup luksUUID /dev/vg_arch/lv_arch
libguestfs: trace: v2v: luks_uuid = "67240fbd-c216-47a1-8fb3-bea96884b0fa"
getline: Inappropriate ioctl for device
virt-v2v-inspector: could not read key from user
```

Why is this second inspection pass prompting for key input from user if the previous used the tmp key created with success?

**Comment by mrnold** [comment]
@rwmjones Do you have any idea about what could be going wrong here?

**Comment by rwmjones** [comment]
Do we have a complete virt-v2v log file?

**Comment by stefanSpectro** [comment]
@rwmjones please see the complete log file attached.  Ends with error `Failed to inspect the disk exit status 1` seemingly caused by `virt-v2v-inspector: could not read key from user` mentioned above.

[completelogs.log](https://github.com/user-attachments/files/22661807/completelogs.log)

**Comment by rwmjones** [comment]
I cannot see the virt-v2v-in-place command line in the log, but presumably MTV passes one or more `--key` parameters to unlock the disk.  However no `--key` parameters are present when virt-v2v-inspector is invoked, so it won't be able to unlock the disk.

**Comment by stefanSpectro** [comment]
Got it, thank you.
I looked in to this more and saw a MTV ticket for this which shows the exact same error: https://issues.redhat.com/browse/MTV-1864 which had a fix merged in to 2.7.8.  PR: https://github.com/kubev2v/forklift/pull/1295

However the file which this fix was merged in to, does not seem to even exist anymore.  Are you able to speak to if this fix still exists in the forklift code base?  I do not see this code anymore and seems to have been removed in 2.8.0
@rwmjones

**Comment by rwmjones** [comment]
Do you mean the bug has reoccurred since 2.7.8?  You don't say what version of forklift or MTV you are using.

It was fixed upstream in forklift in this commit: https://github.com/kubev2v/forklift/commit/36e55c695a23c18f49548a5a0e3a63725b8ea1d4

The same fix still appears to exist in the code, but in a different place now:
https://github.com/kubev2v/forklift/blob/b000de2e097e42401b615c447a1cb6ff02542c79/pkg/virt-v2v/conversion/conversion.go#L100

**Comment by stefanSpectro** [comment]
@rwmjones thank you for your patience on this and we determined we had issues with our versioning.  We corrected this and migration of LUKS VM worked.  Thank you for your help and guidance.
Closing this issue.
